### ISSUE TITLE
Update Ansible version?

### ISSUE THREAD

**Issue by fubarhouse** [geerlingguy/docker-ubuntu1204-ansible#3]
Hey mate!

Would it at all be possible for you to upgrade the version of Ansible to 2.4.0 or later?

I'm working on a new role and this one image is the only one which can't run due to the need for using `include_tasks` vs `include`, not present in pre-2.4.0.

If it's not something you'll consider, could I ask you tell me up front?

You can see it in action here:
* https://travis-ci.org/fubarhouse/ansible-role-rust/builds/309935307

**Comment by geerlingguy** [comment]
It looks like the version on the latest version of the image from Docker Hub is now Ansible 2.5.0:

```
root@b84616035aed:/# ansible --version
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.3 (default, Oct 26 2016, 21:01:49) [GCC 4.6.3]
```

Note that this image is only minimally maintained anymore, since 12.04 is now deprecated :(
